### ISSUE TITLE
tokio-reactor-trait lacks Windows support

### ISSUE THREAD

**Issue by ColinFinck** [amqp-rs/reactor-trait#1]
`tokio-reactor-trait` currently only has a Unix code path implemented. As this code path takes arbitrary handles and wraps them in an `AsyncFd`, Windows support likely depends on https://github.com/tokio-rs/tokio/issues/3781
It's just a pity that lapin 1.x works fine on Windows and lapin 2.x does not, and probably won't for a long time.

**Comment by Keruspe** [comment]
Yes, it's partly linked to this issue indeed.

Wrt lapin:
There's another way of getting the pieces necessary for lapin but I haven't gotten around to it yet. I probably could spend more time more rapidly on it with sponsoring. It's definitely on my TODO for lapin 3.0 which should come later this year.
Lapin 2.0 should work just fine on windows though, if it doesn't please open an issue in the lapin project. Lapin 1.0 didn't use tokio reactor either when on non unix systems

**Comment by ColinFinck** [comment]
> Lapin 2.0 should work just fine on windows though

If I want to move from lapin 1.x with tokio to lapin 2.x, I replace

```
ConnectionProperties::default().with_tokio()
```

by

```
ConnectionProperties::default()
    .with_executor(tokio_executor_trait::Tokio::current())
    .with_reactor(tokio_reactor_trait::Tokio)
```

But this doesn't build on Windows, because `with_reactor` expects an object that implements the `Reactor` trait.
And `tokio-reactor-trait` only implements that trait for the Unix code path. Which is why I opened the bug here.

Can we do anything about that except waiting for https://github.com/tokio-rs/tokio/issues/3781 ?

**Comment by Keruspe** [comment]
If you look closely to tokio-amqp for lapin 1.0, you'll see that the with_reactor is called only on unix too, so for now you can just drop it to have feature parity.

My plan, while waiting for this issue, is to add a supplemental trait in reactor-trait : TcpReactor. It will wrap the reactor's tcp implementation directly, which is available for windows too, instead of registering the tcp stack from libstd in the reactor like we do as of now. Then lapin will accept this as an alternative and prefer it if specified.
Not sure if it'll require 3.0 or not yet.

**Comment by Keruspe** [comment]
Not yet used in lapin, but it'll be addressed by the TcpReactor trait
